### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by amrrs** [gradsflow/chitra#166]
First off, Apologies for opening an issue for this. I'm currently not active on Social Media but wanted a way to share this. 

Second, Thanks so much for this amazing open source library. This is amazing work! Kudos to @aniketmaurya and the contributors. 

Here's my small video contribution to spread the word - https://youtu.be/0RJfKJEXUDg

Once again, I'm sorry for raising an issue for this. please close this issue after you read the message. 
Thanks!

**Comment by aniketmaurya** [comment]
Hey @amrrs, thank you so much for creating this video. This will help us a lot!

Would you mind if we link this to our documentation?

**Comment by amrrs** [comment]
That'll be my honor. Thank you @aniketmaurya
